site_name: Agate
nav:
  - Home: index.md
  - Installation: installation.md
  - Basic: basic.md
  - Advanced:
    - Molecular Dynamics: md.md
    - Phonons: phonons.md
    - Perovskites: perovskites.md
  - qAgate: qagate.md
markdown_extensions:
  - admonition
extra_javascript:
  #- javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
